# Generated by Django 5.2.3 on 2025-07-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
