# Generated by Django 5.2.3 on 2025-07-09 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.problem'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translated_text',
            field=models.TextField(max_length=500),
        ),
    ]
