# Generated by Django 5.2.3 on 2025-07-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tag_alter_translation_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
    ]
